In [5]:
import warnings


warnings.filterwarnings('ignore')

import tensorflow as tf

print(tf.__version__)
import numpy as np

1.14.0


In [23]:
graph = tf.Graph() # or tf.get_default_graph()
session = tf.InteractiveSession(graph = graph)

## Target to implement sigmoid function

```python
z = W*X + b
y = sigmoid(z)
```


In [3]:
x = tf.placeholder(shape = [1,10], dtype = tf.float32, name = 'x')
W = tf.Variable(tf.random_uniform(shape = [10,5], minval= -0.1, maxval = 0.1, dtype= tf.float32), name = 'w')

b = tf.Variable(tf.zeros(shape = [1,5], dtype = tf.float32), name = 'b')

z = tf.matmul(x,W) + b

h = tf.nn.sigmoid(z)


In [4]:
tf.global_variables_initializer().run()

In [11]:
h_eval = session.run([h,], feed_dict= {x:np.random.rand(1,10)})
print(h_eval)
print(type(h_eval))

[array([[0.53276086, 0.4873422 , 0.5293786 , 0.4985795 , 0.48104948]],
      dtype=float32)]
<class 'list'>


In [12]:
session.close()

## Data Pipeline CSV

### steps:
- list of filenames
- filename queue producing filenames for reading the inputs
- a record reader for reading the inputs from queue
- a decoder to decode the read records (JPEG decoder, csv decoder)
- preprocessing(optional)
- output x: a decoded queue

In [48]:
graph = tf.Graph()
session = tf.InteractiveSession(graph = graph)

In [49]:
from glob import glob

filenames = glob('./data/*.txt')
print(filenames)

filename_queue = tf.train.string_input_producer(filenames, capacity = 3, shuffle = True, name = 'string_input_pro')


['./data/1.txt', './data/2.txt', './data/3.txt', './data/4.txt']


In [50]:
reader = tf.TextLineReader()

key, value = reader.read(filename_queue, name = 'text_read_op')

record_defaults = [[-1.0], [-1.0], [-1.0],[-1.0],[-1.0],[-1.0],[-1.0],[-1.0],[-1.0],[-1.0],]

col1, col2, col3, col4, col5, col6, col7, col8, col9, col10 = tf.decode_csv(value, record_defaults = record_defaults)

In [51]:
features = tf.stack([col1, col2, col3, col4, col5, col6, col7, col8, col9, col10])

x= tf.train.shuffle_batch([features], batch_size = 3, capacity = 5, name = 'data_batch', min_after_dequeue = 1, num_threads = 1)


In [52]:
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(coord = coord, sess = session)



### Write the model

In [53]:
W = tf.Variable(tf.random_uniform(shape = [10,5], minval= -0.1, maxval = 0.1, dtype= tf.float32), name = 'w')

b = tf.Variable(shape = [1,5], dtype = tf.float32, initial_value =tf.zeros(shape = [1,5]),name = 'b')

z = tf.matmul(x,W) + b

h = tf.nn.sigmoid(z)


In [54]:
tf.global_variables_initializer().run()

In [58]:
for step in range(5):
    x_eval,h_eval= session.run([x,h])
    print("============Step %d====="%step)
    print("evaluated data: \n",x_eval)
    print()
    
    print("h \n",h_eval)
    print()
    print()
    #print("h: ",h_eval)
    

============Step 0=====
evaluated data: 
 [[12. 22. 32. 42. 16.  6. 17. 18. 19. 10.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 1.  2.  3.  4. 16.  6. 17. 18. 19. 10.]]

h 
 [[0.25494397 0.9553317  0.9835261  0.8793436  0.04499936]
 [0.1982154  0.4991967  0.58653617 0.37489372 0.3031178 ]
 [0.03795338 0.5276239  0.6971744  0.22401138 0.6471871 ]]


============Step 1=====
evaluated data: 
 [[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [11. 12. 13.  4. 16.  6. 17. 18. 19. 10.]
 [11. 12. 13.  4. 16.  6. 17. 18. 19. 10.]]

h 
 [[0.1982154  0.4991967  0.58653617 0.37489372 0.3031178 ]
 [0.02766812 0.77443033 0.8612188  0.57398784 0.60139126]
 [0.02766812 0.77443033 0.8612188  0.5739878  0.60139126]]


============Step 2=====
evaluated data: 
 [[12. 22. 32. 42. 16.  6. 17. 18. 19. 10.]
 [ 1.  2.  3.  4. 16.  6. 17. 18. 19. 10.]
 [11. 12. 13.  4. 16.  6. 17. 18. 19. 10.]]

h 
 [[0.25494397 0.9553317  0.9835261  0.8793436  0.04499936]
 [0.03795338 0.5276239  0.69717443 0.22401139 0.6471871 ]

In [62]:

b = tf.Variable(shape = [1,5], dtype = tf.float32, initial_value = tf.zeros(shape = [1,5]),name = 'b')

In [63]:
print(b)

<tf.Variable 'b_4:0' shape=(1, 5) dtype=float32_ref>
